### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ghost** [Geik-xyz/Tuccar#1]
https://github.com/Geik-xyz/Tuccar/blob/7919ae556226a93c8aad4eda56e3f750ea4a84e8/src/poyrazinan/com/tr/tuccar/listeners/Guis/PlayerProductsListener.java#L34

Checking event.getView().getTitle() to see whether your custom inventory is being used is unsafe, as renaming a chest in an anvil allows users to set their own inventory titles. The correct way to check if your custom inventory is involved with an event is by using custom holders, see here: https://docs.papermc.io/paper/dev/custom-inventory-holder

**Comment by Erissos** [comment]
I am **not** the plugin owner, I updated the plugin to the new version, but thank you for the **information**. It was useful for me. Also, players don't open chests, they open a special menu. _(This message was written with the help of a translation application.)_

**Comment by poyrazinan** [comment]
This plugin is discounted but thank you for send issue
